name    'counsyl-apache'
version '0.8.3'
source  'git://github.counsyl.com/dev/puppet-apache.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Installs the Apache 2 web server'
description 'Installs the Apache 2 web server'
project_page 'https://github.counsyl.com/dev/puppet-apache'

dependency 'counsyl/sys', '>= 0.9.5'
